config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "/questions", to: "questions#ask"
  get "/answers", to: "questions#answer"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def ask
  end

  def answer
    question = params[:question]
   case
    when question.include?("?")
      @answer = "Silly question, get dressed and go to work!"
    when question == "I'm going to work"
      @answer = "Great!"
    else
      @answer = "I don't care, get dressed and go to work!"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<h1>Hello</h1>


<h2 class="bg-warning-subtle"><%=@answer %></h2>

<%= link_to 'Go back to questions', questions_path, class:"btn btn-primary" %>

app/views/questions/ask.html.erb
<div class="mx-auto p-2">
<h1 class="d-flex align-middle justify-content-center p-5">Ask a question</h1>
<form action="/answers" data-turbo="false" class="input-group mx-auto m-5 p-5">
  <input type="text" name="question" class="form-control">
  <input type="submit" class="btn btn-primary">
</form>
</div>